import React from 'react';
import { ArrowRight, Building2, ExternalLink, Info, MapPin, Phone, Search, School, Users } from 'lucide-react';
import { useTheme } from '../context/ThemeContext';

interface DfUnitsSectionProps { onOpenParticipation: (program?: string) => void; }
const FIRST_SEARCH_URL = 'https://www.firstinspires.org/team-event-search';
const SENAI_DF_URL = 'https://www.sistemafibra.org.br/senai/';
const SENAI_DF_EDUCACAO_URL = 'https://sistemafibra.org.br/senai/educacao';
const units = [
  { name: 'SENAI Brasília', region: 'Brasília · SIG', address: 'Setor de Indústrias Gráficas, Quadra 6, Lote 1.100' },
  { name: 'SENAI Brazlândia', region: 'Brazlândia', address: 'Área Especial nº 3 Norte – Parque de Serviços' },
  { name: 'SENAI Gama', region: 'Gama', address: 'Área Especial, Entrequadras 2 e 8 – Setor Sul' },
  { name: 'SENAI Taguatinga', region: 'Taguatinga', address: 'Área Especial nº 2 – Setor C Norte' },
  { name: 'SENAI Sobradinho', region: 'Sobradinho', address: 'Quadra 13, Área Especial nº 3, Lotes A/F' },
];

export const DfUnitsSection: React.FC<DfUnitsSectionProps> = ({ onOpenParticipation }) => {
  const { isDark } = useTheme();
  const card = isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200 shadow-sm';
  return <section id="unidades-df" className={`py-16 sm:py-24 border-t transition-colors ${isDark ? 'bg-slate-900 text-white border-slate-800' : 'bg-slate-50 text-slate-900 border-slate-200'}`}>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="text-center max-w-3xl mx-auto mb-10"><div className={`inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border text-xs font-bold mb-4 ${isDark ? 'bg-blue-500/10 border-blue-500/30 text-blue-300' : 'bg-blue-50 border-blue-200 text-blue-700'}`}><MapPin className="w-3.5 h-3.5" /> ROBÓTICA NO DISTRITO FEDERAL</div><h2 className="text-3xl sm:text-5xl font-black tracking-tight mb-4">ONDE COMEÇAR NO DF</h2><p className={isDark ? 'text-slate-300' : 'text-slate-600'}>Encontre uma unidade, procure equipes e eventos e confirme oportunidades diretamente com os canais oficiais.</p></div>
      <div className={`max-w-4xl mx-auto mb-8 rounded-2xl border p-4 sm:p-5 flex items-start gap-3 ${isDark ? 'bg-blue-500/10 border-blue-500/30 text-blue-100' : 'bg-blue-50 border-blue-200 text-blue-900'}`}><Info className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" /><p className="text-sm leading-relaxed">As unidades abaixo servem como referência de localização. Atividades de robótica, cursos, horários e vagas podem variar; confirme tudo antes de se deslocar.</p></div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4 mb-10">{units.map(unit => <article key={unit.name} className={`rounded-2xl border p-5 ${card}`}><div className="w-10 h-10 rounded-xl bg-blue-700 text-white flex items-center justify-center mb-4"><School className="w-5 h-5" /></div><p className="text-xs font-bold uppercase tracking-wider text-orange-600">{unit.region}</p><h3 className="font-black text-base mt-1 mb-3">{unit.name}</h3><p className={`text-xs leading-relaxed flex items-start gap-2 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}><MapPin className="w-3.5 h-3.5 shrink-0 mt-0.5" /> {unit.address}</p></article>)}</div>
      <div className="grid md:grid-cols-3 gap-4 mb-6">
        <a href="/unidades" className={`rounded-2xl border p-6 transition-all hover:-translate-y-0.5 ${card} hover:border-blue-400`}><Building2 className="w-6 h-6 text-blue-600 mb-4" /><h3 className="text-lg font-black mb-2">Ver todas as unidades</h3><p className={`text-sm leading-relaxed mb-4 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>Abra a página dedicada com orientações e referências das unidades SENAI-DF.</p><span className="inline-flex items-center gap-1.5 text-sm font-bold text-blue-600">Abrir unidades <ArrowRight className="w-4 h-4" /></span></a>
        <a href="/equipes" className={`rounded-2xl border p-6 transition-all hover:-translate-y-0.5 ${card} hover:border-orange-400`}><Users className="w-6 h-6 text-orange-600 mb-4" /><h3 className="text-lg font-black mb-2">Encontrar equipes</h3><p className={`text-sm leading-relaxed mb-4 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>Veja um passo a passo seguro para procurar equipes FIRST® no Distrito Federal.</p><span className="inline-flex items-center gap-1.5 text-sm font-bold text-orange-600">Procurar equipes <ArrowRight className="w-4 h-4" /></span></a>
        <a href="/eventos" className={`rounded-2xl border p-6 transition-all hover:-translate-y-0.5 ${card} hover:border-emerald-400`}><Search className="w-6 h-6 text-emerald-600 mb-4" /><h3 className="text-lg font-black mb-2">Eventos e temporada</h3><p className={`text-sm leading-relaxed mb-4 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>Acompanhe os marcos da temporada e caminhos para verificar eventos oficiais.</p><span className="inline-flex items-center gap-1.5 text-sm font-bold text-emerald-600">Ver eventos <ArrowRight className="w-4 h-4" /></span></a>
      </div>
      <div className={`rounded-3xl border p-6 sm:p-8 ${card}`}><div className="grid lg:grid-cols-12 gap-6 items-center"><div className="lg:col-span-7"><h3 className="text-xl sm:text-2xl font-black mb-3">Canais oficiais do SENAI-DF</h3><p className={`text-sm leading-relaxed mb-4 ${isDark ? 'text-slate-300' : 'text-slate-600'}`}>Para cursos, atendimento e confirmação de oportunidades, use o Sistema Fibra.</p><p className="font-black flex items-center gap-2"><Phone className="w-4 h-4 text-orange-500" /> (61) 4042-6565</p></div><div className="lg:col-span-5 flex flex-col sm:flex-row lg:flex-col gap-3"><a href={SENAI_DF_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-blue-700 hover:bg-blue-600 text-white text-sm font-bold">SENAI-DF oficial <ExternalLink className="w-4 h-4" /></a><a href={SENAI_DF_EDUCACAO_URL} target="_blank" rel="noreferrer" className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border text-sm font-bold ${isDark ? 'border-slate-700 bg-slate-950' : 'border-slate-200 bg-slate-50'}`}>Cursos e educação <ExternalLink className="w-4 h-4" /></a><a href={FIRST_SEARCH_URL} target="_blank" rel="noreferrer" className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border text-sm font-bold ${isDark ? 'border-slate-700 bg-slate-950' : 'border-slate-200 bg-slate-50'}`}>Busca FIRST® <ExternalLink className="w-4 h-4" /></a><button type="button" onClick={() => onOpenParticipation()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-orange-600 hover:bg-orange-500 text-white text-sm font-bold">Como participar <ArrowRight className="w-4 h-4" /></button></div></div></div>
    </div>
  </section>;
};
